name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Root dependencies
        run: |
          npm ci

      - name: Build Root
        run: |
          npm run build

      - name: Install dependencies
        run: |
          npm ci
          cd packages/lexical-playground
          npm ci

      - name: Build
        run: |
          cd packages/lexical-playground
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/lexical-playground/build # Adjust this to your build output directory
